apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: student-app
type: Opaque
data:
  mysql-root-password: cm9vdA==
  mysql-username: c3R1ZGVudF91c2Vy
  mysql-password: c3R1ZGVudF9wYXNzd29yZA==
