apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-backend
  namespace: student-app
  labels:
    app: springboot-backend

spec:
  selector:
    matchLabels: app:springboot-backend

  template:
    metadata:
      labels:
        app: springboot-backend

    spec:
      containers:
        - name: springboot-backend
          image: backend:v1
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: springboot-backend-configmap
            - secretKeyRef:
                name: mysql-secret
                key: mysql-username
            - secretKeyRef:
                name: mysql-secret
                key: mysql-password
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
