apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    app: backend
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: backend
  type: ClusterIP
