apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: shubham1807/backend:v1
        ports:
        - containerPort: 8081
          name: backend
        env:
        - name: DB_HOST   
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
        - name: DB_NAME  
              valueFrom :
                configMapKeyRef:
                  name: db-config
                  key: dbname
            - name: DB_USERNAME  
              valueFrom :
                secretKeyRef:
                  name: mysql-secrets
                  key: username
            - name: DB_PASSWORD 
              valueFrom :
                secretKeyRef:
                  name: mysql-secrets
                  key: password
     
